// Centralized product data for Vow & Veil

export const products = [
    {
        id: 1,
        name: 'Elegant Couple Attire',
        price: '5,999',
        category: 'Couple Sets',
        image: '/products/couple1.jpg',
        createdAt: '2024-06-01T10:00:00Z',
        href: '/collections/couple1',
    },
    {
        id: 2,
        name: 'Bridal Gown Luxe',
        price: '11,999',
        category: 'Bride Dresses',
        image: '/products/couple4.jpg',
        createdAt: '2024-06-03T12:00:00Z',
        href: '/collections/couple4',
    },
    {
        id: 3,
        name: 'Groom Classic Suit',
        price: '5,999',
        category: 'Groom Suits',
        image: '/products/couple6.jpg',
        createdAt: '2024-06-05T09:00:00Z',
        href: '/collections/couple6',
    },
    {
        id: 4,
        name: 'Vintage Ring Set',
        price: '9,999',
        category: 'Accessories',
        image: '/products/couple8.jpg',
        createdAt: '2024-06-07T15:00:00Z',
        href: '/collections/couple8',
    },
    {
        id: 5,
        name: 'Bridal Gown Luxe',
        price: '11,999',
        category: 'Bride Dresses',
        image: '/products/couple4.jpg',
        createdAt: '2024-06-09T11:00:00Z',
        href: '/collections/couple4b',
    },
    {
        id: 6,
        name: 'Ivory Lace Couple Ensemble',
        price: '12,999',
        category: 'Couple Sets',
        image: '/products/couple1.jpg',
        createdAt: '2024-06-10T10:00:00Z',
        href: '/collections/couple1',
    },
    {
        id: 7,
        name: 'Minimalist Bride Gown',
        price: '8,499',
        category: 'Bride Dresses',
        image: '/products/couple2.jpg',
        createdAt: '2024-06-11T10:00:00Z',
        href: '/collections/couple2',
    },
    {
        id: 8,
        name: 'Classic Groom Tuxedo',
        price: '9,999',
        category: 'Groom Suits',
        image: '/products/couple3.jpg',
        createdAt: '2024-06-12T10:00:00Z',
        href: '/collections/couple3',
    }
]; 